Fo 2062 2
navikt/registreringsinformasjon pull request #11
Opened 2019-04-04 07:14 UTC by jcpgithub

2019-04-04 07:54 UTC, alexander-svendsen requested changes

2019-04-04 07:54 UTC, alexander-svendsen commented on src/components/mal/Malhistorikk.tsx
> +const moment = require('moment');
Hvorfor require?

2019-04-04 12:12 UTC, alexander-svendsen reviewed
kan vi kanskje bli kvitt moment ? 
https://github.com/you-dont-need/You-Dont-Need-Momentjs

2019-04-04 12:12 UTC, alexander-svendsen commented on package.json
> +    "chai": "^4.2.0",
Remove it plz

2019-04-04 13:10 UTC, jcpgithub commented on package.json
> +    "chai": "^4.2.0",
Har fjernet

2019-04-04 13:11 UTC, jcpgithub commented on src/components/mal/Malhistorikk.tsx
> +const moment = require('moment');
Tar i bruk date-fns istedefor moment

2019-04-05 07:15 UTC, alexander-svendsen approved these changes

2019-04-05 12:03 UTC, merged