[KAIZEN-0] refaktorering registreringsinfo
navikt/registreringsinformasjon pull request #12
Opened 2019-04-05 11:35 UTC by hakonph

2019-04-05 11:43 UTC, alexander-svendsen requested changes

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/Registreringsinfo.tsx
>  import EndreRegistreringerMock from '../../mock/EndreRegistreringerMock';
Mock ?

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/hjelpekomponeneter/jobbprofilCV.tsx
> +export default function JobbprofilCV(props: {type: string, fremtidigSituasjon: string | null}) {
Lag heller et inferface ut av prop typene. Blir lettere å lese

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/hjelpekomponeneter/hjelpere.tsx
> +import {teksterTilLenker} from "../tekster";
Jeg foreslår å fjerne tekster.. Det er ikke verdt å ha det

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/hjelpekomponeneter/jobbprofilCV.tsx
> +        <Visning viseble={
visible?

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/hjelpekomponeneter/jobbprofilCV.tsx
> +            props.type !== SYKMELDT
Kanskje trekke dette ut i en const ? 
Lettere å lese

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/hjelpekomponeneter/sykefravaer.tsx
> +const Sykefravaer = (props: {type: string}) => (
Tror det er bedre å være konsistent med const vs function.. en miks skaper rot i koden

2019-04-05 11:43 UTC, alexander-svendsen commented on src/components/registreringsinfo/hjelpekomponeneter/sykefravaer.tsx
> +const Sykefravaer = (props: {type: string}) => (
Så enten bruk functions all the way, eller bruk const a = () => {}

2019-04-05 11:57 UTC, jcpgithub approved these changes
👍 bra good. fiks tslint

2019-04-05 11:57 UTC, jcpgithub commented on src/components/registreringsinfo/hjelpekomponeneter/jobbprofilCV.tsx
> +        <Visning viseble={
viseble -> visible

2019-04-05 11:57 UTC, jcpgithub commented on src/components/registreringsinfo/hjelpekomponeneter/moteReferater.tsx
> +    <Visning viseble={
viseble -> visible

2019-04-05 12:02 UTC, jcpgithub requested changes
Fiks tslint

2019-04-09 10:40 UTC, jcpgithub approved these changes

2019-04-09 10:53 UTC, alexander-svendsen approved these changes

2019-04-09 12:24 UTC, merged